services:
  mongo_db:
    image: mongo:8.2.3-noble
    ports:
      - "27017:27017"
    volumes:
      - "./mongo-data:/data/db"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=1010110

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    command: redis-server
    restart: unless-stopped